
PROJECT_DIR := $(PWD)
OBJDIR := $(PROJECT_DIR)/obj
ROOT_DIR := $(realpath $(PROJECT_DIR)/../../../../)
PROCESSOR_DIR := $(realpath $(PROJECT_DIR)/../../)
BUILDTOOLS_DIR := $(ROOT_DIR)/buildtools/



#check if we have a C lint tool
LINT=

FINDLINT:=$(shell which lint)

ifeq ($(FINDLINT),)
FINDLINT:=$(shell which splint)
endif

ifneq ($(FINDLINT),)
LINT    = $(FINDLINT)
endif

INCLUDES = -I$(PROCESSOR_DIR)

